### ISSUE TITLE
Convert Minetest lines to a format VSCode can parse.

### ISSUE THREAD

**Issue by Poikilos** [expertmm/outputinspector#26]
VSCode can jump to a line if the error is in the following format:
```
File "/home/owner/git/outputinspector/outputinspector/noqt.py", line 340, in __init__
```
...maybe not? only file opens and there is no line jumping (only path is underlined) in the following case:
- make bad code that is utilized in a test
- run tests using Potion icon on left bar
- If unittest is configured correctly (such as in the included code-workspace), it will try to run tests.
  - if it is not configured, it should display a Configure Tests button.
    - to choose the tests folder in that wizard, the **tests folder must be in the root** of the repo, not in the module (probably better, to prevent distribution, anyway) 
- it will say say Test Discovery failure, see OUTPUT, Python
- Click OUTPUT tab at bottom, then choose Python category
- The output will appear like the output below (line jumping fails, only file is underlined):
```
2023-08-12 11:58:33.111 [error] Error discovering unittest tests:
 Traceback (most recent call last):
  File "/home/owner/.vscode/extensions/ms-python.python-2023.14.0/pythonFiles/testing_tools/unittest_discovery.py", line 42, in <module>
    suite = loader.discover(start_dir, pattern=pattern, top_level_dir=top_level_dir)
  File "/usr/lib64/python3.10/unittest/loader.py", line 349, in discover
    tests = list(self._find_tests(start_dir, pattern))
  File "/usr/lib64/python3.10/unittest/loader.py", line 405, in _find_tests
    tests, should_recurse = self._find_test_path(
  File "/usr/lib64/python3.10/unittest/loader.py", line 460, in _find_test_path
    return self.loadTestsFromModule(module, pattern=pattern), False
  File "/usr/lib64/python3.10/unittest/loader.py", line 124, in loadTestsFromModule
    tests.append(self.loadTestsFromTestCase(obj))
  File "/usr/lib64/python3.10/unittest/loader.py", line 93, in loadTestsFromTestCase
    loaded_suite = self.suiteClass(map(testCaseClass, testCaseNames))
  File "/usr/lib64/python3.10/unittest/suite.py", line 24, in __init__
    self.addTests(tests)
  File "/usr/lib64/python3.10/unittest/suite.py", line 57, in addTests
    for test in tests:
  File "/home/owner/git/outputinspector/tests/test_minetest.py", line 72, in __init__
    self.inspector = OutputInspector()
  File "/home/owner/git/outputinspector/outputinspector/__init__.py", line 645, in __init__
    QMainWindow.__init__(
  File "/home/owner/git/outputinspector/outputinspector/noqt.py", line 867, in __init__
    _ui_loader(self, self._ui, ui_file)
  File "/home/owner/git/outputinspector/outputinspector/noqt.py", line 783, in _ui_loader
    _ui_subtree(ui, self, node, ui_file)
  File "/home/owner/git/outputinspector/outputinspector/noqt.py", line 703, in _ui_subtree
    subObj = thisType(parentWidget)
  File "/home/owner/git/outputinspector/outputinspector/noqt.py", line 568, in __init__
    ttk.Label.__init__(self, *args, **kwargs)
  File "/usr/lib64/python3.10/tkinter/ttk.py", line 754, in __init__
    Widget.__init__(self, master, "ttk::label", kw)
  File "/usr/lib64/python3.10/tkinter/ttk.py", line 552, in __init__
    tkinter.Widget.__init__(self, master, widgetname, kw=kw)
  File "/usr/lib64/python3.10/tkinter/__init__.py", line 2595, in __init__
    self._setup(master, cnf)
  File "/usr/lib64/python3.10/tkinter/__init__.py", line 2564, in _setup
    self.tk = master.tk
AttributeError: 'OutputInspector' object has no attribute 'tk'

```

Yet this works (in a regular run, not testing):

(jumps to line; path and line are underlined):
```
Traceback (most recent call last):
  File "/home/owner/git/world_clock/world_clock", line 27, in <module>
    from worldclocktk import main
  File "/home/owner/git/world_clock/worldclocktk/__init__.py", line 232, in <module>
    myShare = os.path.join(SHARE, MY_LUID)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen posixpath>", line 76, in join
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

**Comment by Poikilos** [comment]
done in e15647fe30cd05ac5b115a20d86d814e7e430a1f
